"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: commonInfo.msg.dds_
  IDL file: commoninfo.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import teleai_dds_wrapper.commonInfo


@dataclass
@annotate.final
@annotate.autoid("sequential")
class commonCamera_224(idl.IdlStruct, typename="commonInfo.msg.dds_.commonCamera_224"):
    image: types.array[types.byte, 150528]


@dataclass
@annotate.final
@annotate.autoid("sequential")
class commonCamera_640480(idl.IdlStruct, typename="commonInfo.msg.dds_.commonCamera_640480"):
    image: types.array[types.byte, 921600]


@dataclass
@annotate.final
@annotate.autoid("sequential")
class float_7d(idl.IdlStruct, typename="commonInfo.msg.dds_.float_7d"):
    data: types.array[types.float32, 7]


@dataclass
@annotate.final
@annotate.autoid("sequential")
class uint_7d(idl.IdlStruct, typename="commonInfo.msg.dds_.uint_7d"):
    data: types.array[types.float32, 7]


@dataclass
@annotate.final
@annotate.autoid("sequential")
class uint_1d(idl.IdlStruct, typename="commonInfo.msg.dds_.uint_1d"):
    data: types.array[types.byte, 1]


@dataclass
@annotate.final
@annotate.autoid("sequential")
class float_1d(idl.IdlStruct, typename="commonInfo.msg.dds_.float_1d"):
    data: types.array[types.float32, 1]


@dataclass
@annotate.final
@annotate.autoid("sequential")
class uint_100d(idl.IdlStruct, typename="commonInfo.msg.dds_.uint_100d"):
    data: types.array[types.byte, 100]


@dataclass
@annotate.final
@annotate.autoid("sequential")
class process_state(idl.IdlStruct, typename="commonInfo.msg.dds_.process_state"):
    name: str
    annotate.key("name")
    state: types.int32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class roboticArm_single_control_info(idl.IdlStruct, typename="commonInfo.msg.dds_.roboticArm_single_control_info"):
    arm_joint_q: 'commonInfo.msg.dds_.float_7d'
    gripper_action: 'commonInfo.msg.dds_.uint_1d'


@dataclass
@annotate.final
@annotate.autoid("sequential")
class roboticArm_single_state_info(idl.IdlStruct, typename="commonInfo.msg.dds_.roboticArm_single_state_info"):
    arm_joint_q: 'commonInfo.msg.dds_.float_7d'
    gripper_state: 'commonInfo.msg.dds_.float_1d'


@dataclass
@annotate.final
@annotate.autoid("sequential")
class roboticArm_double_control_info(idl.IdlStruct, typename="commonInfo.msg.dds_.roboticArm_double_control_info"):
    left_arm_q: 'commonInfo.msg.dds_.float_7d'
    right_arm_q: 'commonInfo.msg.dds_.float_7d'
    left_gripper_action: 'commonInfo.msg.dds_.uint_1d'
    right_gripper_action: 'commonInfo.msg.dds_.uint_1d'


@dataclass
@annotate.final
@annotate.autoid("sequential")
class roboticArm_double_state_info(idl.IdlStruct, typename="commonInfo.msg.dds_.roboticArm_double_state_info"):
    left_arm_q: 'commonInfo.msg.dds_.float_7d'
    right_arm_q: 'commonInfo.msg.dds_.float_7d'
    left_gripper: 'commonInfo.msg.dds_.float_1d'
    right_gripper: 'commonInfo.msg.dds_.float_1d'


@dataclass
@annotate.final
@annotate.autoid("sequential")
class roboticArm_double_all_state_info(idl.IdlStruct, typename="commonInfo.msg.dds_.roboticArm_double_all_state_info"):
    left_arm_q: 'commonInfo.msg.dds_.float_7d'
    right_arm_q: 'commonInfo.msg.dds_.float_7d'
    left_arm_dq: 'commonInfo.msg.dds_.float_7d'
    right_arm_dq: 'commonInfo.msg.dds_.float_7d'
    left_arm_tau: 'commonInfo.msg.dds_.float_7d'
    right_arm_tau: 'commonInfo.msg.dds_.float_7d'
    left_gripper: 'commonInfo.msg.dds_.float_1d'
    right_gripper: 'commonInfo.msg.dds_.float_1d'
    left_gripper_vel: 'commonInfo.msg.dds_.float_1d'
    right_gripper_vel: 'commonInfo.msg.dds_.float_1d'


